function out1 = get_u5(lambda_12,mu_9,mu_10)
%GET_U5
%    OUT1 = GET_U5(LAMBDA_12,MU_9,MU_10)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Apr-2025 19:15:24

out1 = lambda_12.*(-1.631333197993098e+1)-mu_9.*3.942388561816653+mu_10.*3.942388561816653;
