function out1 = get_u3(lambda_9,mu_9,mu_10,q_ant_1,q_ant_2,q_ant_3,q_ant_4)
%GET_U3
%    OUT1 = GET_U3(LAMBDA_9,MU_9,MU_10,Q_ANT_1,Q_ANT_2,Q_ANT_3,Q_ANT_4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Apr-2025 16:08:31

t2 = q_ant_1.^2;
t3 = q_ant_1.^3;
t4 = q_ant_2.^2;
t6 = q_ant_2.^3;
t7 = q_ant_3.^2;
t9 = q_ant_4.^2;
t5 = t2.^2;
t8 = t4.^2;
et1 = t2.*-1.015e+5-t4.*1.015e+5+t5.*1.015e+5+t8.*1.015e+5-q_ant_1.*q_ant_3.*4.698e+4+q_ant_1.*q_ant_4.*4.698e+4-q_ant_2.*q_ant_3.*4.698e+4-q_ant_2.*q_ant_4.*4.698e+4+q_ant_3.*t3.*9.396e+4-q_ant_4.*t3.*9.396e+4+q_ant_3.*t6.*9.396e+4+q_ant_4.*t6.*9.396e+4+t2.*t4.*2.03e+5+t2.*t7.*1.01848e+5+t2.*t9.*1.01848e+5+t4.*t7.*1.01848e+5+t4.*t9.*1.01848e+5+q_ant_2.*q_ant_3.*t2.*9.396e+4+q_ant_1.*q_ant_3.*t4.*9.396e+4+q_ant_2.*q_ant_4.*t2.*9.396e+4-q_ant_1.*q_ant_4.*t4.*9.396e+4;
et2 = q_ant_3.*q_ant_4.*t2.*8.7e+4-q_ant_1.*q_ant_2.*t7.*8.7e+4-q_ant_3.*q_ant_4.*t4.*8.7e+4+q_ant_1.*q_ant_2.*t9.*8.7e+4+5.6625e+4;
et3 = lambda_9.*1.5e+4+mu_9.*5.6625e+4-mu_10.*5.6625e+4-mu_9.*t2.*1.015e+5+mu_10.*t2.*1.015e+5-mu_9.*t4.*1.015e+5+mu_9.*t5.*1.015e+5+mu_10.*t4.*1.015e+5-mu_10.*t5.*1.015e+5+mu_9.*t8.*1.015e+5-mu_10.*t8.*1.015e+5-mu_9.*q_ant_1.*q_ant_3.*4.698e+4+mu_9.*q_ant_1.*q_ant_4.*4.698e+4-mu_9.*q_ant_2.*q_ant_3.*4.698e+4+mu_10.*q_ant_1.*q_ant_3.*4.698e+4-mu_9.*q_ant_2.*q_ant_4.*4.698e+4-mu_10.*q_ant_1.*q_ant_4.*4.698e+4+mu_10.*q_ant_2.*q_ant_3.*4.698e+4+mu_10.*q_ant_2.*q_ant_4.*4.698e+4+mu_9.*q_ant_3.*t3.*9.396e+4-mu_9.*q_ant_4.*t3.*9.396e+4;
et4 = mu_10.*q_ant_3.*t3.*-9.396e+4+mu_10.*q_ant_4.*t3.*9.396e+4+mu_9.*q_ant_3.*t6.*9.396e+4+mu_9.*q_ant_4.*t6.*9.396e+4-mu_10.*q_ant_3.*t6.*9.396e+4-mu_10.*q_ant_4.*t6.*9.396e+4+mu_9.*t2.*t4.*2.03e+5-mu_10.*t2.*t4.*2.03e+5+mu_9.*t2.*t7.*1.01848e+5-mu_10.*t2.*t7.*1.01848e+5+mu_9.*t2.*t9.*1.01848e+5+mu_9.*t4.*t7.*1.01848e+5-mu_10.*t2.*t9.*1.01848e+5-mu_10.*t4.*t7.*1.01848e+5+mu_9.*t4.*t9.*1.01848e+5-mu_10.*t4.*t9.*1.01848e+5+mu_9.*q_ant_2.*q_ant_3.*t2.*9.396e+4+mu_9.*q_ant_1.*q_ant_3.*t4.*9.396e+4;
et5 = mu_9.*q_ant_2.*q_ant_4.*t2.*9.396e+4-mu_10.*q_ant_2.*q_ant_3.*t2.*9.396e+4-mu_9.*q_ant_1.*q_ant_4.*t4.*9.396e+4+mu_9.*q_ant_3.*q_ant_4.*t2.*8.7e+4-mu_10.*q_ant_1.*q_ant_3.*t4.*9.396e+4-mu_10.*q_ant_2.*q_ant_4.*t2.*9.396e+4-mu_9.*q_ant_1.*q_ant_2.*t7.*8.7e+4+mu_10.*q_ant_1.*q_ant_4.*t4.*9.396e+4-mu_10.*q_ant_3.*q_ant_4.*t2.*8.7e+4-mu_9.*q_ant_3.*q_ant_4.*t4.*8.7e+4+mu_10.*q_ant_1.*q_ant_2.*t7.*8.7e+4+mu_9.*q_ant_1.*q_ant_2.*t9.*8.7e+4+mu_10.*q_ant_3.*q_ant_4.*t4.*8.7e+4-mu_10.*q_ant_1.*q_ant_2.*t9.*8.7e+4;
out1 = 1.0./(et1+et2).^2.*(et3+et4+et5).*-7.5e+3;
end
