function out1 = get_mu_13(lambda_12,u_5)
%GET_MU_13
%    OUT1 = GET_MU_13(LAMBDA_12,U_5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Apr-2025 16:29:09

out1 = lambda_12.*(-1.2e+2./2.9e+1)-u_5.*2.536533333333333e-1;
