function out1 = get_u4(lambda_11,mu_11,mu_12)
%GET_U4
%    OUT1 = GET_U4(LAMBDA_11,MU_11,MU_12)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Apr-2025 14:20:42

out1 = lambda_11.*(-3.108485514468555e+1)-mu_11.*3.942388561816653+mu_12.*3.942388561816653;
