function out1 = get_u4(lambda_11,mu_11,mu_12)
%GET_U4
%    OUT1 = GET_U4(LAMBDA_11,MU_11,MU_12)

<<<<<<< HEAD
%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Apr-2025 16:29:10
=======
%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Apr-2025 16:08:31
>>>>>>> 9fc6132dc936935b374998339f3cc9a9f45acff7

out1 = lambda_11.*(-3.108485514468555e+1)-mu_11.*3.942388561816653+mu_12.*3.942388561816653;
end
