function out1 = get_u4(lambda_11,mu_7,mu_8)
%GET_U4
%    OUT1 = GET_U4(LAMBDA_11,MU_7,MU_8)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Apr-2025 19:15:24

out1 = lambda_11.*(-3.108485514468555e+1)-mu_7.*3.942388561816653+mu_8.*3.942388561816653;
