function out1 = get_mu_1(lambda_7,q_ant_1,q_ant_2,q_ant_3,q_ant_4,u_1)
%GET_MU_1
%    OUT1 = GET_MU_1(LAMBDA_7,Q_ANT_1,Q_ANT_2,Q_ANT_3,Q_ANT_4,U_1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Apr-2025 16:35:11

t2 = q_ant_2.^2;
t3 = q_ant_3.^2;
t4 = q_ant_1.*q_ant_2.*2.0;
t5 = q_ant_1.*q_ant_3.*2.0;
t6 = q_ant_2.*q_ant_4.*2.0;
t7 = q_ant_3.*q_ant_4.*2.0;
t11 = q_ant_1.*q_ant_2.*(2.9e+1./2.0e+1);
t12 = q_ant_3.*q_ant_4.*(2.9e+1./2.0e+1);
t15 = q_ant_1.*q_ant_3.*(2.03e+2./6.0e+1);
t16 = q_ant_2.*q_ant_4.*(2.03e+2./6.0e+1);
t20 = q_ant_1.*q_ant_2.*(7.83e+2./5.0e+2);
t21 = q_ant_1.*q_ant_3.*(7.83e+2./5.0e+2);
t22 = q_ant_2.*q_ant_4.*(7.83e+2./5.0e+2);
t23 = q_ant_3.*q_ant_4.*(7.83e+2./5.0e+2);
t30 = q_ant_1.*q_ant_2.*3.394933333333333;
t31 = q_ant_3.*q_ant_4.*3.394933333333333;
t8 = t2.*2.0;
t9 = t3.*2.0;
t10 = -t6;
t13 = t2.*(2.9e+1./2.0e+1);
t14 = t3.*(2.9e+1./2.0e+1);
t17 = t4+t7;
t18 = -t15;
t24 = t2.*(7.83e+2./5.0e+2);
t25 = t3.*(7.83e+2./5.0e+2);
t26 = -t21;
t27 = -t22;
t33 = t2.*3.394933333333333;
t34 = t3.*3.394933333333333;
t19 = t5+t10;
t28 = -t24;
t29 = -t25;
t32 = t8+t9-1.0;
t35 = t13+t14+t22+t26+t30+t31-2.9e+1./4.0e+1;
t37 = t11+t12+t21+t27+t33+t34-1.697466666666667;
t36 = t16+t18+t20+t23+t28+t29+7.83e+2./1.0e+3;
t38 = t17.*t35;
t41 = t32.*t37;
t39 = t19.*t36;
t40 = -t39;
t42 = t38+t40+t41+2.5e+1./1.2e+1;
out1 = t42.*u_1.*-2.0-lambda_7./t42;
end
