function out1 = get_mu_7(lambda_8,q_ant_1,q_ant_2,q_ant_3,q_ant_4,u_2)
%GET_MU_7
%    OUT1 = GET_MU_7(LAMBDA_8,Q_ANT_1,Q_ANT_2,Q_ANT_3,Q_ANT_4,U_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Apr-2025 16:29:08

t2 = q_ant_1.^2;
t3 = q_ant_3.^2;
t4 = q_ant_1.*q_ant_2.*2.0;
t5 = q_ant_1.*q_ant_4.*2.0;
t6 = q_ant_2.*q_ant_3.*2.0;
t7 = q_ant_3.*q_ant_4.*2.0;
t11 = q_ant_1.*q_ant_2.*(2.9e+1./2.0e+1);
t12 = q_ant_3.*q_ant_4.*(2.9e+1./2.0e+1);
t16 = q_ant_1.*q_ant_4.*(2.03e+2./6.0e+1);
t17 = q_ant_2.*q_ant_3.*(2.03e+2./6.0e+1);
t22 = q_ant_1.*q_ant_2.*(7.83e+2./5.0e+2);
t23 = q_ant_1.*q_ant_4.*(7.83e+2./5.0e+2);
t24 = q_ant_2.*q_ant_3.*(7.83e+2./5.0e+2);
t25 = q_ant_3.*q_ant_4.*(7.83e+2./5.0e+2);
t29 = q_ant_1.*q_ant_2.*3.394933333333333;
t30 = q_ant_3.*q_ant_4.*3.394933333333333;
t8 = t2.*2.0;
t9 = t3.*2.0;
t10 = -t7;
t13 = t2.*(2.9e+1./2.0e+1);
t14 = t3.*(2.9e+1./2.0e+1);
t15 = -t12;
t18 = t5+t6;
t26 = t2.*(7.83e+2./5.0e+2);
t27 = t3.*(7.83e+2./5.0e+2);
t28 = -t22;
t32 = t2.*3.394933333333333;
t33 = t3.*3.394933333333333;
t34 = -t29;
t19 = -t13;
t20 = -t14;
t21 = t4+t10;
t31 = t8+t9-1.0;
t36 = t16+t17+t25+t26+t27+t28-7.83e+2./1.0e+3;
t37 = t11+t15+t23+t24+t32+t33-1.697466666666667;
t35 = t19+t20+t23+t24+t30+t34+2.9e+1./4.0e+1;
t38 = t18.*t36;
t41 = t31.*t37;
t39 = t21.*t35;
t40 = -t39;
t42 = t38+t40+t41+2.5e+1./1.2e+1;
out1 = t42.*u_2.*-2.0-lambda_8./t42;
