function out1 = get_u1(lambda_7,mu_5,mu_6,q_ant_1,q_ant_2,q_ant_3,q_ant_4)
%GET_U1
%    OUT1 = GET_U1(LAMBDA_7,MU_5,MU_6,Q_ANT_1,Q_ANT_2,Q_ANT_3,Q_ANT_4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Apr-2025 14:23:05

t2 = q_ant_1.^2;
t3 = q_ant_2.^2;
t4 = q_ant_2.^3;
t5 = q_ant_3.^2;
t7 = q_ant_3.^3;
t8 = q_ant_4.^2;
t6 = t3.^2;
t9 = t5.^2;
et1 = t3.*-2.5462e+4-t5.*2.5462e+4+t6.*2.5462e+4+t9.*2.5462e+4-q_ant_1.*q_ant_2.*1.0875e+4-q_ant_1.*q_ant_3.*1.1745e+4+q_ant_2.*q_ant_4.*1.1745e+4-q_ant_3.*q_ant_4.*1.0875e+4+q_ant_1.*t4.*2.175e+4+q_ant_1.*t7.*2.349e+4-q_ant_4.*t4.*2.349e+4+q_ant_4.*t7.*2.175e+4+t2.*t3.*2.5462e+4+t2.*t5.*2.5375e+4+t3.*t5.*5.0924e+4+t3.*t8.*2.5375e+4+t5.*t8.*2.5462e+4+q_ant_1.*q_ant_3.*t3.*2.349e+4-q_ant_2.*q_ant_3.*t2.*2.349e+4+q_ant_1.*q_ant_2.*t5.*2.175e+4+q_ant_1.*q_ant_4.*t3.*2.349e+4-q_ant_1.*q_ant_4.*t5.*2.349e+4+q_ant_3.*q_ant_4.*t3.*2.175e+4;
et2 = q_ant_2.*q_ant_4.*t5.*-2.349e+4+q_ant_2.*q_ant_3.*t8.*2.349e+4+q_ant_1.*q_ant_2.*q_ant_3.*q_ant_4.*1.74e+2+1.4178e+4;
et3 = lambda_7.*3.75e+3+mu_5.*1.4178e+4-mu_6.*1.4178e+4-mu_5.*t3.*2.5462e+4+mu_6.*t3.*2.5462e+4-mu_5.*t5.*2.5462e+4+mu_5.*t6.*2.5462e+4+mu_6.*t5.*2.5462e+4-mu_6.*t6.*2.5462e+4+mu_5.*t9.*2.5462e+4-mu_6.*t9.*2.5462e+4-mu_5.*q_ant_1.*q_ant_2.*1.0875e+4-mu_5.*q_ant_1.*q_ant_3.*1.1745e+4+mu_6.*q_ant_1.*q_ant_2.*1.0875e+4+mu_6.*q_ant_1.*q_ant_3.*1.1745e+4+mu_5.*q_ant_2.*q_ant_4.*1.1745e+4-mu_5.*q_ant_3.*q_ant_4.*1.0875e+4-mu_6.*q_ant_2.*q_ant_4.*1.1745e+4+mu_6.*q_ant_3.*q_ant_4.*1.0875e+4+mu_5.*q_ant_1.*t4.*2.175e+4-mu_6.*q_ant_1.*t4.*2.175e+4+mu_5.*q_ant_1.*t7.*2.349e+4;
et4 = mu_5.*q_ant_4.*t4.*-2.349e+4-mu_6.*q_ant_1.*t7.*2.349e+4+mu_6.*q_ant_4.*t4.*2.349e+4+mu_5.*q_ant_4.*t7.*2.175e+4-mu_6.*q_ant_4.*t7.*2.175e+4+mu_5.*t2.*t3.*2.5462e+4-mu_6.*t2.*t3.*2.5462e+4+mu_5.*t2.*t5.*2.5375e+4+mu_5.*t3.*t5.*5.0924e+4-mu_6.*t2.*t5.*2.5375e+4-mu_6.*t3.*t5.*5.0924e+4+mu_5.*t3.*t8.*2.5375e+4-mu_6.*t3.*t8.*2.5375e+4+mu_5.*t5.*t8.*2.5462e+4-mu_6.*t5.*t8.*2.5462e+4+mu_5.*q_ant_1.*q_ant_3.*t3.*2.349e+4-mu_5.*q_ant_2.*q_ant_3.*t2.*2.349e+4+mu_5.*q_ant_1.*q_ant_2.*t5.*2.175e+4+mu_5.*q_ant_1.*q_ant_4.*t3.*2.349e+4-mu_6.*q_ant_1.*q_ant_3.*t3.*2.349e+4;
et5 = mu_6.*q_ant_2.*q_ant_3.*t2.*2.349e+4-mu_6.*q_ant_1.*q_ant_2.*t5.*2.175e+4-mu_6.*q_ant_1.*q_ant_4.*t3.*2.349e+4-mu_5.*q_ant_1.*q_ant_4.*t5.*2.349e+4+mu_5.*q_ant_3.*q_ant_4.*t3.*2.175e+4-mu_5.*q_ant_2.*q_ant_4.*t5.*2.349e+4+mu_6.*q_ant_1.*q_ant_4.*t5.*2.349e+4-mu_6.*q_ant_3.*q_ant_4.*t3.*2.175e+4+mu_6.*q_ant_2.*q_ant_4.*t5.*2.349e+4+mu_5.*q_ant_2.*q_ant_3.*t8.*2.349e+4-mu_6.*q_ant_2.*q_ant_3.*t8.*2.349e+4+mu_5.*q_ant_1.*q_ant_2.*q_ant_3.*q_ant_4.*1.74e+2-mu_6.*q_ant_1.*q_ant_2.*q_ant_3.*q_ant_4.*1.74e+2;
out1 = 1.0./(et1+et2).^2.*(et3+et4+et5).*-1.875e+3;
