function out1 = get_u2(lambda_8,mu_7,mu_8,q_ant_1,q_ant_2,q_ant_3,q_ant_4)
%GET_U2
%    OUT1 = GET_U2(LAMBDA_8,MU_7,MU_8,Q_ANT_1,Q_ANT_2,Q_ANT_3,Q_ANT_4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Apr-2025 16:29:10

t2 = q_ant_1.^2;
t3 = q_ant_1.^3;
t4 = q_ant_2.^2;
t6 = q_ant_3.^2;
t7 = q_ant_3.^3;
t8 = q_ant_4.^2;
t5 = t2.^2;
t9 = t6.^2;
et1 = t2.*-2.5462e+4+t5.*2.5462e+4-t6.*2.5462e+4+t9.*2.5462e+4-q_ant_1.*q_ant_2.*1.0875e+4-q_ant_1.*q_ant_4.*1.1745e+4-q_ant_2.*q_ant_3.*1.1745e+4+q_ant_3.*q_ant_4.*1.0875e+4+q_ant_2.*t3.*2.175e+4+q_ant_4.*t3.*2.349e+4+q_ant_2.*t7.*2.349e+4-q_ant_4.*t7.*2.175e+4+t2.*t4.*2.5462e+4+t2.*t6.*5.0924e+4+t2.*t8.*2.5375e+4+t4.*t6.*2.5375e+4+t6.*t8.*2.5462e+4+q_ant_2.*q_ant_3.*t2.*2.349e+4-q_ant_1.*q_ant_3.*t4.*2.349e+4-q_ant_2.*q_ant_4.*t2.*2.349e+4+q_ant_1.*q_ant_2.*t6.*2.175e+4-q_ant_3.*q_ant_4.*t2.*2.175e+4+q_ant_1.*q_ant_4.*t6.*2.349e+4;
et2 = q_ant_1.*q_ant_3.*t8.*2.349e+4+q_ant_2.*q_ant_4.*t6.*2.349e+4-q_ant_1.*q_ant_2.*q_ant_3.*q_ant_4.*1.74e+2+1.4178e+4;
et3 = lambda_8.*3.75e+3+mu_7.*1.4178e+4-mu_8.*1.4178e+4-mu_7.*t2.*2.5462e+4+mu_8.*t2.*2.5462e+4+mu_7.*t5.*2.5462e+4-mu_7.*t6.*2.5462e+4-mu_8.*t5.*2.5462e+4+mu_8.*t6.*2.5462e+4+mu_7.*t9.*2.5462e+4-mu_8.*t9.*2.5462e+4-mu_7.*q_ant_1.*q_ant_2.*1.0875e+4+mu_8.*q_ant_1.*q_ant_2.*1.0875e+4-mu_7.*q_ant_1.*q_ant_4.*1.1745e+4-mu_7.*q_ant_2.*q_ant_3.*1.1745e+4+mu_8.*q_ant_1.*q_ant_4.*1.1745e+4+mu_8.*q_ant_2.*q_ant_3.*1.1745e+4+mu_7.*q_ant_3.*q_ant_4.*1.0875e+4-mu_8.*q_ant_3.*q_ant_4.*1.0875e+4+mu_7.*q_ant_2.*t3.*2.175e+4-mu_8.*q_ant_2.*t3.*2.175e+4+mu_7.*q_ant_4.*t3.*2.349e+4;
et4 = mu_8.*q_ant_4.*t3.*-2.349e+4+mu_7.*q_ant_2.*t7.*2.349e+4-mu_8.*q_ant_2.*t7.*2.349e+4-mu_7.*q_ant_4.*t7.*2.175e+4+mu_8.*q_ant_4.*t7.*2.175e+4+mu_7.*t2.*t4.*2.5462e+4-mu_8.*t2.*t4.*2.5462e+4+mu_7.*t2.*t6.*5.0924e+4-mu_8.*t2.*t6.*5.0924e+4+mu_7.*t2.*t8.*2.5375e+4+mu_7.*t4.*t6.*2.5375e+4-mu_8.*t2.*t8.*2.5375e+4-mu_8.*t4.*t6.*2.5375e+4+mu_7.*t6.*t8.*2.5462e+4-mu_8.*t6.*t8.*2.5462e+4+mu_7.*q_ant_2.*q_ant_3.*t2.*2.349e+4-mu_7.*q_ant_1.*q_ant_3.*t4.*2.349e+4-mu_7.*q_ant_2.*q_ant_4.*t2.*2.349e+4-mu_8.*q_ant_2.*q_ant_3.*t2.*2.349e+4+mu_7.*q_ant_1.*q_ant_2.*t6.*2.175e+4;
et5 = mu_7.*q_ant_3.*q_ant_4.*t2.*-2.175e+4+mu_8.*q_ant_1.*q_ant_3.*t4.*2.349e+4+mu_8.*q_ant_2.*q_ant_4.*t2.*2.349e+4-mu_8.*q_ant_1.*q_ant_2.*t6.*2.175e+4+mu_8.*q_ant_3.*q_ant_4.*t2.*2.175e+4+mu_7.*q_ant_1.*q_ant_4.*t6.*2.349e+4+mu_7.*q_ant_1.*q_ant_3.*t8.*2.349e+4+mu_7.*q_ant_2.*q_ant_4.*t6.*2.349e+4-mu_8.*q_ant_1.*q_ant_4.*t6.*2.349e+4-mu_8.*q_ant_1.*q_ant_3.*t8.*2.349e+4-mu_8.*q_ant_2.*q_ant_4.*t6.*2.349e+4-mu_7.*q_ant_1.*q_ant_2.*q_ant_3.*q_ant_4.*1.74e+2+mu_8.*q_ant_1.*q_ant_2.*q_ant_3.*q_ant_4.*1.74e+2;
out1 = 1.0./(et1+et2).^2.*(et3+et4+et5).*-1.875e+3;
