function out1 = get_u5(lambda_12,mu_13,mu_14)
%GET_U5
%    OUT1 = GET_U5(LAMBDA_12,MU_13,MU_14)

<<<<<<< HEAD
%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Apr-2025 16:29:10
=======
%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Apr-2025 16:08:31
>>>>>>> 9fc6132dc936935b374998339f3cc9a9f45acff7

out1 = lambda_12.*(-1.631333197993098e+1)-mu_13.*3.942388561816653+mu_14.*3.942388561816653;
end
