function out1 = get_mu_5(lambda_9,q_ant_1,q_ant_2,q_ant_3,q_ant_4,u_3)
%GET_MU_5
%    OUT1 = GET_MU_5(LAMBDA_9,Q_ANT_1,Q_ANT_2,Q_ANT_3,Q_ANT_4,U_3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Apr-2025 18:52:18

t2 = q_ant_1.^2;
t3 = q_ant_2.^2;
t4 = q_ant_1.*q_ant_3.*2.0;
t5 = q_ant_1.*q_ant_4.*2.0;
t6 = q_ant_2.*q_ant_3.*2.0;
t7 = q_ant_2.*q_ant_4.*2.0;
t11 = q_ant_1.*q_ant_3.*(2.9e+1./2.0e+1);
t12 = q_ant_1.*q_ant_4.*(2.9e+1./2.0e+1);
t13 = q_ant_2.*q_ant_3.*(2.9e+1./2.0e+1);
t14 = q_ant_2.*q_ant_4.*(2.9e+1./2.0e+1);
t20 = q_ant_1.*q_ant_3.*(7.83e+2./5.0e+2);
t21 = q_ant_1.*q_ant_4.*(7.83e+2./5.0e+2);
t22 = q_ant_2.*q_ant_3.*(7.83e+2./5.0e+2);
t23 = q_ant_2.*q_ant_4.*(7.83e+2./5.0e+2);
t29 = q_ant_1.*q_ant_3.*3.394933333333333;
t30 = q_ant_1.*q_ant_4.*3.394933333333333;
t31 = q_ant_2.*q_ant_3.*3.394933333333333;
t32 = q_ant_2.*q_ant_4.*3.394933333333333;
t8 = t2.*2.0;
t9 = t3.*2.0;
t10 = -t6;
t15 = -t13;
t16 = t4+t7;
t17 = t2.*(2.03e+2./6.0e+1);
t18 = t3.*(2.03e+2./6.0e+1);
t24 = t2.*(7.83e+2./5.0e+2);
t25 = t3.*(7.83e+2./5.0e+2);
t26 = -t21;
t34 = -t31;
t19 = t5+t10;
t27 = -t24;
t28 = -t25;
t33 = t8+t9-1.0;
t35 = t17+t18+t20+t22+t23+t26-2.03e+2./1.2e+2;
t36 = t12+t15+t24+t25+t29+t32-7.83e+2./1.0e+3;
t37 = t11+t14+t27+t28+t30+t34+7.83e+2./1.0e+3;
t38 = t16.*t36;
t39 = t33.*t35;
t40 = t19.*t37;
t41 = t38+t39+t40+2.5e+1./1.2e+1;
out1 = t41.*u_3.*-2.0-lambda_9./t41;
