function out1 = get_mu_11(lambda_11,u_4)
%GET_MU_11
%    OUT1 = GET_MU_11(LAMBDA_11,U_4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Apr-2025 16:29:09

out1 = lambda_11.*(-7.884777123633305)-u_4.*2.536533333333333e-1;
