function out1 = get_mu_7(lambda_11,u_4)
%GET_MU_7
%    OUT1 = GET_MU_7(LAMBDA_11,U_4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Apr-2025 16:35:12

out1 = lambda_11.*(-7.884777123633305)-u_4.*2.536533333333333e-1;
end
